# SPDX-FileCopyrightText: 2026 British Club Challenge authors
# SPDX-License-Identifier: MPL-2.0
# Outputs for the bccweb2 tfstate bootstrap.
#
# `backend_config_hcl` is a copy-pasteable HCL snippet that the operator drops
# into `iac/env/<env>.backend.hcl`. The root config consumes it via
# `terraform -chdir=iac init -backend-config=env/<env>.backend.hcl`.

output "resource_group_name" {
  description = "Name of the bootstrap resource group that holds the tfstate storage account."
  value       = azapi_resource.bootstrap_rg.name
}

output "storage_account_name" {
  description = "Name of the storage account hosting the tfstate blob container."
  value       = azapi_resource.tfstate_sa.name
}

output "container_name" {
  description = "Name of the blob container that holds tfstate blobs."
  value       = azapi_resource.tfstate_container.name
}

output "backend_config_hcl" {
  description = "Ready-to-paste contents for iac/env/<env>.backend.hcl. Replace <env> with the stamp name (e.g. prod) when setting `key`."
  value       = <<-EOT
    # Generated by iac/bootstrap. Paste into iac/env/<env>.backend.hcl and set `key`.
    resource_group_name  = "${azapi_resource.bootstrap_rg.name}"
    storage_account_name = "${azapi_resource.tfstate_sa.name}"
    container_name       = "${azapi_resource.tfstate_container.name}"
    key                  = "<env>.tfstate"
    use_azuread_auth     = true
  EOT
}

# ─── Terraform UMIs + GitHub OIDC outputs ────────────────────────────────────
#
# `terraform_umi_client_ids` holds the appId of each env's UMI — the value
# GitHub Actions passes as `client-id` to `azure/login@v3`. Not secrets —
# OIDC binds each clientId to its federated subject claim.
# `terraform_umi_principal_ids` are the UMIs' object/principal IDs, useful
# for downstream RBAC. The resource IDs are handy for `az identity ...`
# commands. All maps are keyed by env (terraform_umis key).

output "terraform_umi_client_ids" {
  description = "Map env → application (client) ID of that env's Terraform UMI. Pass as AZURE_CLIENT_ID to azure/login@v3 (not a secret — OIDC binds it to the federated subject)."
  value       = { for k, v in azapi_resource.tf_umi : k => v.output.properties.clientId }
}

output "terraform_umi_principal_ids" {
  description = "Map env → object (principal) ID of that env's Terraform UMI. Used for downstream RBAC role assignments."
  value       = { for k, v in azapi_resource.tf_umi : k => v.output.properties.principalId }
}

output "terraform_umi_resource_ids" {
  description = "Map env → full Azure resource ID of that env's Terraform UMI."
  value       = { for k, v in azapi_resource.tf_umi : k => v.id }
}

output "pre_created_rg_names" {
  description = "Map platform-<env>/stamp-<env> → resource group name. These RGs are owned by bootstrap; common and service stacks reference them by interpolated name/ID (never creating or reading them)."
  value       = { for k, v in azapi_resource.pre_created_rg : k => v.name }
}

output "pre_created_rg_ids" {
  description = "Map platform-<env>/stamp-<env> → resource group Azure ID."
  value       = { for k, v in azapi_resource.pre_created_rg : k => v.id }
}

output "tenant_id" {
  description = "Azure AD tenant ID. Pass as AZURE_TENANT_ID to azure/login@v2."
  value       = data.azapi_client_config.current.tenant_id
}

output "subscription_id" {
  description = "Azure subscription ID that owns the bootstrap RG and the pre-created env RGs. Pass as AZURE_SUBSCRIPTION_ID to azure/login@v3."
  value       = data.azapi_client_config.current.subscription_id
}

output "github_actions_setup" {
  description = "Copy-pasteable operator runbook for wiring GitHub Actions to the per-env Terraform UMIs via OIDC. None of these values are secret."
  value       = <<-EOT
    GitHub Actions OIDC setup for the per-env Terraform UMIs
    ========================================================

    One UMI per environment; each owns ONLY its env's platform + stamp RGs
    (RG-scoped Owner, never subscription scope) plus tfstate blob access.

    1. GitHub environment secrets (3 per environment, 6 total for dev+prod):
%{if var.manage_github_secrets~}
       Created automatically by Terraform — no manual paste needed.
       Verify in the GitHub UI at:
%{for e in var.github_environments~}
         https://github.com/${var.github_repo}/settings/environments/${e}
%{endfor~}
       Each environment receives ITS OWN clientId (values differ per env):
%{for k, v in var.terraform_umis~}
         ${v.github_env}: AZURE_CLIENT_ID = ${azapi_resource.tf_umi[k].output.properties.clientId}
%{endfor~}
       All environments share:
         AZURE_TENANT_ID       = ${data.azapi_client_config.current.tenant_id}
         AZURE_SUBSCRIPTION_ID = ${data.azapi_client_config.current.subscription_id}
%{else~}
       Automatic creation is disabled (manage_github_secrets = false).
       Set these as GitHub ENVIRONMENT-level secrets manually (each env gets
       its own clientId — repo-level secrets cannot express this):
%{for k, v in var.terraform_umis~}
         ${v.github_env}: AZURE_CLIENT_ID = ${azapi_resource.tf_umi[k].output.properties.clientId}
%{endfor~}
       All environments share:
         AZURE_TENANT_ID       = ${data.azapi_client_config.current.tenant_id}
         AZURE_SUBSCRIPTION_ID = ${data.azapi_client_config.current.subscription_id}
%{endif~}

    2. Federated credentials exist for these GitHub environments (subject
       claim repo:${var.github_repo}:environment:<env>):
%{for k, v in var.terraform_umis~}
         - ${v.github_env} (UMI id-bccweb-terraform-${k})
%{endfor~}

       To add another env: add a new entry to `terraform_umis` (and the
       matching name to `github_environments`) in terraform.tfvars, then
       re-run `terraform -chdir=iac/bootstrap apply`.

    3. Each workflow job that needs Azure access MUST set:
         permissions:
           id-token: write   # required for OIDC
           contents: read
         environment: <env-name>  # e.g. prod — must match a federated env

    4. Example azure/login@v3 step:
         - uses: azure/login@v3
           with:
             client-id: $${{ secrets.AZURE_CLIENT_ID }}
             tenant-id: $${{ secrets.AZURE_TENANT_ID }}
             subscription-id: $${{ secrets.AZURE_SUBSCRIPTION_ID }}
  EOT
}

output "github_environments_created" {
  description = "List of GitHub environment names that Terraform created/adopted on this apply. Empty when manage_github_secrets = false. Useful for downstream automation that needs to enumerate the federated envs."
  value       = var.manage_github_secrets ? var.github_environments : []
}
