# Outputs for the bccweb2 tfstate bootstrap.
#
# `backend_config_hcl` is a copy-pasteable HCL snippet that the operator drops
# into `iac/env/<env>.backend.hcl`. The root config consumes it via
# `terraform -chdir=iac init -backend-config=env/<env>.backend.hcl`.

output "resource_group_name" {
  description = "Name of the bootstrap resource group that holds the tfstate storage account."
  value       = azapi_resource.bootstrap_rg.name
}

output "storage_account_name" {
  description = "Name of the storage account hosting the tfstate blob container."
  value       = azapi_resource.tfstate_sa.name
}

output "container_name" {
  description = "Name of the blob container that holds tfstate blobs."
  value       = azapi_resource.tfstate_container.name
}

output "backend_config_hcl" {
  description = "Ready-to-paste contents for iac/env/<env>.backend.hcl. Replace <env> with the stamp name (e.g. prod) when setting `key`."
  value       = <<-EOT
    # Generated by iac/bootstrap. Paste into iac/env/<env>.backend.hcl and set `key`.
    resource_group_name  = "${azapi_resource.bootstrap_rg.name}"
    storage_account_name = "${azapi_resource.tfstate_sa.name}"
    container_name       = "${azapi_resource.tfstate_container.name}"
    key                  = "<env>.tfstate"
    use_azuread_auth     = true
  EOT
}
