# SPDX-FileCopyrightText: 2026 British Club Challenge authors
# SPDX-License-Identifier: MPL-2.0
# Generated by iac/bootstrap; non-secret and must be committed after bootstrap apply.

env_umi_principal_ids = {
  prod    = "c8a83558-5ac4-482d-83b0-9949197192ce"
  shared  = "345bde99-4586-41d2-8b38-714929c3bc00"
  staging = "f656fadd-a200-4009-aaa1-1bbaa1076f33"
}
