# SPDX-FileCopyrightText: 2026 British Club Challenge authors
# SPDX-License-Identifier: MPL-2.0
# Generated by iac/bootstrap; non-secret and must be committed after bootstrap apply.

env_umi_principal_ids = {
  prod    = "a1dcd40a-c33c-4ca3-80b1-644dc3b2315f"
  shared  = "74029935-aa0c-466c-b8ea-38551c00b5cf"
  staging = "4eabcaaf-5340-41b7-9ed2-7b47ebeaa7cd"
}
